version: '3.8'
services:
  interactive-music-3d:
    build: .
    image: your-dockerhub-username/interactive-music-3d:latest
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - LOG_DIR=/app/logs
      - PORT=${WEB_PORT:-3000}
    volumes:
      - /mnt/user/appdata/interactive-music-3d/logs:/app/logs
      - /mnt/user/appdata/interactive-music-3d/uploads:/app/uploads
      - /mnt/user/appdata/interactive-music-3d/config:/app/config
      - /mnt/user/appdata/interactive-music-3d/playwright:/root/.cache/ms-playwright
      - /mnt/user/appdata/interactive-music-3d/.next-cache:/app/.next/cache
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
