name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Quick checks for all PRs and main branch - under 10 minutes
  quick-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npm run lint
      - run: npm run build
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next
          if-no-files-found: error
          retention-days: 1
      - name: Install Playwright browsers and system dependencies
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm test
        env:
          CI: true

  # Full test suite - only runs on staging branch
  full-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    needs: quick-checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next
          if-no-files-found: error
      - name: List downloaded build
        run: ls -al .next | head
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
      - name: Install system Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        continue-on-error: true
      - name: Install Playwright dependencies
        run: npx playwright install-deps
        continue-on-error: true
      - name: Run full E2E test suite
        run: npm run test:e2e
        env:
          CI: true
      - name: Run visual regression tests
        run: npm run test:visual
        env:
          CI: true
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-videos
          path: test-results/
          retention-days: 30
