name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/interactive-music-3d:latest

      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      UNRAID_HOST: ${{ secrets.UNRAID_HOST }}
      UNRAID_USER: ${{ secrets.UNRAID_USER }}
      UNRAID_SSH_KEY: ${{ secrets.UNRAID_SSH_KEY }}

    steps:
      - name: Deploy to Unraid via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.UNRAID_HOST }}
          username: ${{ env.UNRAID_USER }}
          key: ${{ env.UNRAID_SSH_KEY }}
          script: |
            cd /mnt/user/appdata/interactive-music-3d
            docker-compose pull
            docker-compose up -d
